# Generated by Django 5.1.1 on 2026-01-30 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الخبر', max_length=200)),
                ('excerpt', models.TextField(help_text='ملخص قصير للخبر (يظهر في الكارد)', max_length=500)),
                ('content', models.TextField(blank=True, help_text='المحتوى الكامل للخبر (اختياري)', null=True)),
                ('image', models.ImageField(help_text='صورة الخبر', upload_to='news/')),
                ('date', models.DateField(help_text='تاريخ الخبر')),
                ('link', models.URLField(blank=True, help_text='رابط خارجي للخبر (اختياري)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)')),
                ('is_published', models.BooleanField(default=True, help_text='هل منشور؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='أوائل ثانوية عامة', max_length=200)),
                ('year', models.PositiveIntegerField(help_text='السنة الدراسية (مثلاً 2025)', validators=[django.core.validators.MinValueValidator(2020)])),
                ('image', models.ImageField(help_text='صورة جماعية للأوائل', upload_to='top_students/')),
                ('description', models.TextField(blank=True, help_text='وصف اختياري', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)')),
                ('is_active', models.BooleanField(default=True, help_text='هل يظهر في الصفحة الرئيسية؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top Student Image',
                'verbose_name_plural': 'Top Students Images',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم الكتاب', max_length=200)),
                ('description', models.TextField(blank=True, help_text='وصف الكتاب', null=True)),
                ('cover_image', models.ImageField(help_text='صورة غلاف الكتاب', upload_to='books/')),
                ('pdf_file', models.FileField(blank=True, help_text='ملف الكتاب PDF (اختياري)', null=True, upload_to='books/pdfs/')),
                ('external_link', models.URLField(blank=True, help_text='رابط خارجي للكتاب (اختياري)', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='سعر الكتاب (0 = مجاني)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('term', models.CharField(blank=True, help_text='الترم (مثلاً: الترم الأول، الترم الثاني)', max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)')),
                ('is_published', models.BooleanField(default=True, help_text='هل منشور؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(help_text='الصفوف الدراسية المتاحة لها الكتاب', related_name='books', to='study.grade')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم الباقة (مثلاً: شهر، ترم، سنة)', max_length=100)),
                ('duration_type', models.CharField(choices=[('month', 'شهر'), ('term', 'ترم'), ('year', 'سنة')], default='month', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='السعر بالجنيه', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='وصف الباقة', null=True)),
                ('features', models.JSONField(default=list, help_text='قائمة المميزات ["الفيديوهات", "الاختبارات", "دعم فني"]')),
                ('is_popular', models.BooleanField(default=False, help_text='هل هي الباقة الأكثر شيوعاً؟')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)')),
                ('is_active', models.BooleanField(default=True, help_text='هل متاحة للاشتراك؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(blank=True, help_text='الصفوف المتاحة لهذه الباقة (اختياري)', related_name='packages', to='study.grade')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['order', 'price'],
            },
        ),
    ]
