"""
Django settings for Elfezya_Bgd project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()  # تحميل متغيرات البيئة من ملف .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-*kg&-x)0cy3q5=31%)1gx68v*z)6vu__p1s@_*j2di00ubr7u(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if os.environ.get("DJANGO_ALLOWED_HOSTS") else []


# Application definition

INSTALLED_APPS = [
    "corsheaders",  # ضعها في الأعلى كما هو موصى به
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "storages",
    "study",
    "accounts",
    "contenet",
    "nested_admin",
    "landing",
]

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_ACCESS_KEY_ID = "<YOUR_R2_ACCESS_KEY>"
AWS_SECRET_ACCESS_KEY = "<YOUR_R2_SECRET_KEY>"
AWS_STORAGE_BUCKET_NAME = "<YOUR_R2_BUCKET_NAME>"
AWS_S3_REGION_NAME = "auto"   # أو أي قيمة مناسبة
AWS_S3_ENDPOINT_URL = "https://<ACCOUNT_ID>.r2.cloudflarestorage.com"  # endpoint R2
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"  # أو virtual حسب إعدادك
AWS_DEFAULT_ACL = None

AUTH_USER_MODEL = 'accounts.CustomUser'
MIDDLEWARE = [
    # cors middleware should be as high as possible (before CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "Elfezya_Bgd.middleware.dev_coop.DevCoopMiddleware",
]



# في الإنتاج عيّن CORS_ALLOWED_ORIGINS إلى قائمة الدومينات المسموح بها واتبعه
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
      "http://localhost:5173",
    "http://127.0.0.1:5173",
]


from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "content-type",
]

# Sessions cookie policy (تعديل على حسب بيئة التطوير/الإنتاج)
SESSION_COOKIE_SAMESITE = "Lax"   # أو "None" مع SESSION_COOKIE_SECURE=True على HTTPS
SESSION_COOKIE_SECURE = False     # True في الإنتاج مع https
CSRF_COOKIE_SECURE = False

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # مفيد للوصول من admin
"rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}

# settings.py - وضع بسيط (development)
# بعض النسخ من Django تدعم الإعداد التالي:
# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
# وإلا يمكنك إضافة ميدلوير صغير لتعيين الهيدر على الاستجابات:


# Google client id (ضعه في environment ثم اقرأه هنا)
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "308731366221-kl6ecrhgej9uu1bos28vab8t6o3hh38q.apps.googleusercontent.com")


# Simple JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

ROOT_URLCONF = "Elfezya_Bgd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Elfezya_Bgd.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# افتراضياً sqlite للتطوير — استبدله بإعدادات Postgres/MySQL في الإنتاج
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'elfezya'),
        'USER': os.getenv('DB_USER', 'root'),  # أو المستخدم اللي أنشأته
        'PASSWORD': os.getenv('DB_PASS', '1234'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# لو تحب تضبط الـ timezone لمصر:
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Africa/Cairo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# إعداد Cloudflare R2 (S3-compatible) باستخدام django-storages
# يفضّل تعيين القيم الحقيقية كمتغيرات بيئية بدلاً من تركها hardcoded


# أي إعدادات إضافية لسهولة التطوير/أمان يمكن وضعها هنا
# مثال: CORS_ALLOWED_ORIGINS, ALLOWED_HOSTS, DEBUG وغيرها يمكن التحكم بها من المتغيرات البيئية.
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "youremail@gmail.com"
# EMAIL_HOST_PASSWORD = "your-app-password"  # استخدم App Password
# DEFAULT_FROM_EMAIL = "Platform <youremail@gmail.com>"
