# Generated by Django 5.1.1 on 2026-01-30 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exp', 'explain'), ('rev', 'revision')], default='exp', help_text='نوع الامتحان: شرح أو مراجعة', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('timer_enabled', models.BooleanField(default=True)),
                ('auto_submit_on_expire', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = Quick Exam (before solution video), 1 = Full Exam (after solution video)')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('submitted', 'submitted'), ('graded', 'graded'), ('auto_submitted', 'auto_submitted')], default='in_progress', max_length=30)),
                ('calculated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_answers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='exams', to='study.grade'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('thumbnail_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='lessons', to='study.grade')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='الدرس المرتبط (إلزامي للامتحانات الشرح، اختياري للمراجعة)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='study.lesson'),
        ),
        migrations.CreateModel(
            name='LessonPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='study.lesson')),
            ],
            options={
                'ordering': ('order', 'title'),
                'unique_together': {('lesson', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Which lesson part this exam belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='study.lessonpart'),
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exp', 'explain'), ('sol', 'solution'), ('rev', 'revision')], default='exp', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=2000)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='study.lesson')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='study.lessonpart')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PaidExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('exam_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('mcq_single', 'MCQ single'), ('mcq_multi', 'MCQ multiple'), ('tf', 'True/False'), ('essay', 'Essay')], default='mcq_single', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.exam')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='study.question')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('video_link', models.URLField(blank=True, help_text='رابط فيديو المراجعة', max_length=2000, null=True)),
                ('photo_link', models.URLField(blank=True, help_text='رابط صورة المراجعة', max_length=2000, null=True)),
                ('photo_file', models.ImageField(blank=True, help_text='ارفع صورة من الجهاز (اختياري - سيتم استخدامها بدلاً من الرابط إذا وجدت)', null=True, upload_to='revisions/photos/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='revisions', to='study.grade')),
                ('lesson', models.ForeignKey(blank=True, help_text='الدرس المرتبط (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='study.lesson')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='sections', to='study.grade')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='study.section'),
        ),
        migrations.CreateModel(
            name='SingleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('group_title', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice_id', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_choice_ids', models.JSONField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.paidexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.singlevideo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'slug')},
        ),
    ]
